/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AptHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AptProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BowerGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BowerHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BowerProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CocoapodsProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ConanProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CondaProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DockerGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DockerHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DockerProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitlfsHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GoGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GoProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HelmHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HelmProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MavenGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MavenHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MavenProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NpmGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NpmHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NpmProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NugetGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NugetHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NugetProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *P2Proxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RawGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RawHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RawProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RubygemsGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RubygemsHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RubygemsProxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *YumGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *YumHosted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *YumProxy) Hub() {}
