// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleInitParameters struct {

	// (String) The description of the routing rule
	// The description of the routing rule
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) Matchers is a list of regular expressions used to identify request paths that are allowed or blocked (depending on above mode)
	// Matchers is a list of regular expressions used to identify request paths that are allowed or blocked (depending on above mode)
	// +listType=set
	Matchers []*string `json:"matchers,omitempty" tf:"matchers,omitempty"`

	// (String) The mode describe how to hande with mathing requests. Possible values: BLOCK or ALLOW Default: BLOCK
	// The mode describe how to hande with mathing requests. Possible values: `BLOCK` or `ALLOW` Default: `BLOCK`
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The name of the routing rule
	// The name of the routing rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RuleObservation struct {

	// (String) The description of the routing rule
	// The description of the routing rule
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Used to identify resource at nexus
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Matchers is a list of regular expressions used to identify request paths that are allowed or blocked (depending on above mode)
	// Matchers is a list of regular expressions used to identify request paths that are allowed or blocked (depending on above mode)
	// +listType=set
	Matchers []*string `json:"matchers,omitempty" tf:"matchers,omitempty"`

	// (String) The mode describe how to hande with mathing requests. Possible values: BLOCK or ALLOW Default: BLOCK
	// The mode describe how to hande with mathing requests. Possible values: `BLOCK` or `ALLOW` Default: `BLOCK`
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The name of the routing rule
	// The name of the routing rule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RuleParameters struct {

	// (String) The description of the routing rule
	// The description of the routing rule
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) Matchers is a list of regular expressions used to identify request paths that are allowed or blocked (depending on above mode)
	// Matchers is a list of regular expressions used to identify request paths that are allowed or blocked (depending on above mode)
	// +kubebuilder:validation:Optional
	// +listType=set
	Matchers []*string `json:"matchers,omitempty" tf:"matchers,omitempty"`

	// (String) The mode describe how to hande with mathing requests. Possible values: BLOCK or ALLOW Default: BLOCK
	// The mode describe how to hande with mathing requests. Possible values: `BLOCK` or `ALLOW` Default: `BLOCK`
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) The name of the routing rule
	// The name of the routing rule
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// RuleSpec defines the desired state of Rule
type RuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleInitParameters `json:"initProvider,omitempty"`
}

// RuleStatus defines the observed state of Rule.
type RuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rule is the Schema for the Rules API. Use this resource to create a Nexus Routing Rule.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nexus}
type Rule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.matchers) || (has(self.initProvider) && has(self.initProvider.matchers))",message="spec.forProvider.matchers is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RuleSpec   `json:"spec"`
	Status RuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleList contains a list of Rules
type RuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rule `json:"items"`
}

// Repository type metadata.
var (
	Rule_Kind             = "Rule"
	Rule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rule_Kind}.String()
	Rule_KindAPIVersion   = Rule_Kind + "." + CRDGroupVersion.String()
	Rule_GroupVersionKind = CRDGroupVersion.WithKind(Rule_Kind)
)

func init() {
	SchemeBuilder.Register(&Rule{}, &RuleList{})
}
