apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: BowerProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/bowerproxy
  labels:
    testing.upbound.io/example-name: bower_io
  name: bower-io
spec:
  forProvider:
    httpClient:
    - autoBlock: true
      blocked: false
    name: bower-io
    negativeCache:
    - enabled: true
      ttl: 1440
    online: true
    proxy:
    - contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://registry.bower.io
    rewritePackageUrls: true
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
