apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: CocoapodsProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/cocoapodsproxy
  labels:
    testing.upbound.io/example-name: cocoapods_org
  name: cocoapods-org
spec:
  forProvider:
    httpClient:
    - autoBlock: true
      blocked: false
    name: cocoapods-org
    negativeCache:
    - enabled: true
      ttl: 1440
    online: true
    proxy:
    - contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://cocoapods.org/
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
