apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: GoGroup
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/gogroup
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    group:
    - memberNames:
      - ${nexus_repository_go_proxy.golang_org.name}
    name: go-group
    online: true
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true

---

apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: GoProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/gogroup
  labels:
    testing.upbound.io/example-name: golang_org
  name: golang-org
spec:
  forProvider:
    httpClient:
    - autoBlock: true
      blocked: false
    name: golang-org
    negativeCache:
    - enabled: true
      ttl: 1440
    online: true
    proxy:
    - contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://proxy.golang.org/
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
