apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: HelmProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/helmproxy
  labels:
    testing.upbound.io/example-name: kubernetes_charts
  name: kubernetes-charts
spec:
  forProvider:
    httpClient:
    - autoBlock: true
      blocked: false
    name: kubernetes-charts
    negativeCache:
    - enabled: true
      ttl: 1440
    online: true
    proxy:
    - contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://kubernetes-charts.storage.googleapis.com/
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
