apiVersion: repository.nexus.adrp.xyz/v1alpha1
kind: NpmGroup
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/npmgroup
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    group:
    - memberNames:
      - ${nexus_repository_npm_hosted.internal.name}
    name: npm-group
    online: true
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true

---

apiVersion: repository.nexus.adrp.xyz/v1alpha1
kind: NpmHosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/npmgroup
  labels:
    testing.upbound.io/example-name: internal
  name: internal
spec:
  forProvider:
    name: internal
    online: true
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
      writePolicy: ALLOW
