apiVersion: repository.nexus.adrp.xyz/v1alpha1
kind: NugetProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/nugetproxy
  labels:
    testing.upbound.io/example-name: nuget_org
  name: nuget-org
spec:
  forProvider:
    httpClient:
    - autoBlock: true
      blocked: false
    name: nuget-org
    negativeCache:
    - enabled: true
      ttl: 1440
    nugetVersion: V3
    online: true
    proxy:
    - contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://api.nuget.org/v3/index.json
    queryCacheItemMaxAge: 3600
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
