apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: RawHosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/rawhosted
  labels:
    testing.upbound.io/example-name: internal
  name: internal
spec:
  forProvider:
    name: raw-internal
    online: true
    storage:
    - blobStoreName: default
      strictContentTypeValidation: false
      writePolicy: ALLOW
