apiVersion: repository.nexus.adrp.xyz/v1alpha1
kind: RubygemsProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/rubygemsproxy
  labels:
    testing.upbound.io/example-name: rubygems_org
  name: rubygems-org
spec:
  forProvider:
    httpClient:
    - autoBlock: true
      blocked: false
    name: rubygems-org
    negativeCache:
    - enabled: true
      ttl: 1440
    online: true
    proxy:
    - contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://rubygems.org
    storage:
    - blobStoreName: default
      strictContentTypeValidation: true
