apiVersion: security.nexus.crossplane.io/v1alpha1
kind: UserToken
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/usertoken
  labels:
    testing.upbound.io/example-name: nexus
  name: nexus
spec:
  forProvider:
    enabled: true
    protectContent: false
