apiVersion: nexus.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: nexus-credentials
      key: credentials
      namespace: crossplane-system
