//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Anonymous) DeepCopyInto(out *Anonymous) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Anonymous.
func (in *Anonymous) DeepCopy() *Anonymous {
	if in == nil {
		return nil
	}
	out := new(Anonymous)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Anonymous) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousInitParameters) DeepCopyInto(out *AnonymousInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousInitParameters.
func (in *AnonymousInitParameters) DeepCopy() *AnonymousInitParameters {
	if in == nil {
		return nil
	}
	out := new(AnonymousInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousList) DeepCopyInto(out *AnonymousList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Anonymous, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousList.
func (in *AnonymousList) DeepCopy() *AnonymousList {
	if in == nil {
		return nil
	}
	out := new(AnonymousList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymousList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousObservation) DeepCopyInto(out *AnonymousObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousObservation.
func (in *AnonymousObservation) DeepCopy() *AnonymousObservation {
	if in == nil {
		return nil
	}
	out := new(AnonymousObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousParameters) DeepCopyInto(out *AnonymousParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousParameters.
func (in *AnonymousParameters) DeepCopy() *AnonymousParameters {
	if in == nil {
		return nil
	}
	out := new(AnonymousParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousSpec) DeepCopyInto(out *AnonymousSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousSpec.
func (in *AnonymousSpec) DeepCopy() *AnonymousSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousStatus) DeepCopyInto(out *AnonymousStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousStatus.
func (in *AnonymousStatus) DeepCopy() *AnonymousStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymousStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelector) DeepCopyInto(out *ContentSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelector.
func (in *ContentSelector) DeepCopy() *ContentSelector {
	if in == nil {
		return nil
	}
	out := new(ContentSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContentSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelectorInitParameters) DeepCopyInto(out *ContentSelectorInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelectorInitParameters.
func (in *ContentSelectorInitParameters) DeepCopy() *ContentSelectorInitParameters {
	if in == nil {
		return nil
	}
	out := new(ContentSelectorInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelectorList) DeepCopyInto(out *ContentSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContentSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelectorList.
func (in *ContentSelectorList) DeepCopy() *ContentSelectorList {
	if in == nil {
		return nil
	}
	out := new(ContentSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContentSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelectorObservation) DeepCopyInto(out *ContentSelectorObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelectorObservation.
func (in *ContentSelectorObservation) DeepCopy() *ContentSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(ContentSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelectorParameters) DeepCopyInto(out *ContentSelectorParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelectorParameters.
func (in *ContentSelectorParameters) DeepCopy() *ContentSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(ContentSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelectorSpec) DeepCopyInto(out *ContentSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelectorSpec.
func (in *ContentSelectorSpec) DeepCopy() *ContentSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(ContentSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentSelectorStatus) DeepCopyInto(out *ContentSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentSelectorStatus.
func (in *ContentSelectorStatus) DeepCopy() *ContentSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(ContentSelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ldap) DeepCopyInto(out *Ldap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ldap.
func (in *Ldap) DeepCopy() *Ldap {
	if in == nil {
		return nil
	}
	out := new(Ldap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ldap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapInitParameters) DeepCopyInto(out *LdapInitParameters) {
	*out = *in
	if in.AuthRealm != nil {
		in, out := &in.AuthRealm, &out.AuthRealm
		*out = new(string)
		**out = **in
	}
	if in.AuthSchema != nil {
		in, out := &in.AuthSchema, &out.AuthSchema
		*out = new(string)
		**out = **in
	}
	if in.AuthUsername != nil {
		in, out := &in.AuthUsername, &out.AuthUsername
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRetryDelaySeconds != nil {
		in, out := &in.ConnectionRetryDelaySeconds, &out.ConnectionRetryDelaySeconds
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionTimeoutSeconds != nil {
		in, out := &in.ConnectionTimeoutSeconds, &out.ConnectionTimeoutSeconds
		*out = new(float64)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupIDAttribute != nil {
		in, out := &in.GroupIDAttribute, &out.GroupIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberFormat != nil {
		in, out := &in.GroupMemberFormat, &out.GroupMemberFormat
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectClass != nil {
		in, out := &in.GroupObjectClass, &out.GroupObjectClass
		*out = new(string)
		**out = **in
	}
	if in.GroupSubtree != nil {
		in, out := &in.GroupSubtree, &out.GroupSubtree
		*out = new(bool)
		**out = **in
	}
	if in.GroupType != nil {
		in, out := &in.GroupType, &out.GroupType
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupsAsRoles != nil {
		in, out := &in.LdapGroupsAsRoles, &out.LdapGroupsAsRoles
		*out = new(bool)
		**out = **in
	}
	if in.MaxIncidentCount != nil {
		in, out := &in.MaxIncidentCount, &out.MaxIncidentCount
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.UseTrustStore != nil {
		in, out := &in.UseTrustStore, &out.UseTrustStore
		*out = new(bool)
		**out = **in
	}
	if in.UserBaseDn != nil {
		in, out := &in.UserBaseDn, &out.UserBaseDn
		*out = new(string)
		**out = **in
	}
	if in.UserEmailAddressAttribute != nil {
		in, out := &in.UserEmailAddressAttribute, &out.UserEmailAddressAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserLdapFilter != nil {
		in, out := &in.UserLdapFilter, &out.UserLdapFilter
		*out = new(string)
		**out = **in
	}
	if in.UserMemberOfAttribute != nil {
		in, out := &in.UserMemberOfAttribute, &out.UserMemberOfAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectClass != nil {
		in, out := &in.UserObjectClass, &out.UserObjectClass
		*out = new(string)
		**out = **in
	}
	if in.UserPasswordAttribute != nil {
		in, out := &in.UserPasswordAttribute, &out.UserPasswordAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserRealNameAttribute != nil {
		in, out := &in.UserRealNameAttribute, &out.UserRealNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserSubtree != nil {
		in, out := &in.UserSubtree, &out.UserSubtree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapInitParameters.
func (in *LdapInitParameters) DeepCopy() *LdapInitParameters {
	if in == nil {
		return nil
	}
	out := new(LdapInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapList) DeepCopyInto(out *LdapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ldap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapList.
func (in *LdapList) DeepCopy() *LdapList {
	if in == nil {
		return nil
	}
	out := new(LdapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LdapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapObservation) DeepCopyInto(out *LdapObservation) {
	*out = *in
	if in.AuthRealm != nil {
		in, out := &in.AuthRealm, &out.AuthRealm
		*out = new(string)
		**out = **in
	}
	if in.AuthSchema != nil {
		in, out := &in.AuthSchema, &out.AuthSchema
		*out = new(string)
		**out = **in
	}
	if in.AuthUsername != nil {
		in, out := &in.AuthUsername, &out.AuthUsername
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRetryDelaySeconds != nil {
		in, out := &in.ConnectionRetryDelaySeconds, &out.ConnectionRetryDelaySeconds
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionTimeoutSeconds != nil {
		in, out := &in.ConnectionTimeoutSeconds, &out.ConnectionTimeoutSeconds
		*out = new(float64)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupIDAttribute != nil {
		in, out := &in.GroupIDAttribute, &out.GroupIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberFormat != nil {
		in, out := &in.GroupMemberFormat, &out.GroupMemberFormat
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectClass != nil {
		in, out := &in.GroupObjectClass, &out.GroupObjectClass
		*out = new(string)
		**out = **in
	}
	if in.GroupSubtree != nil {
		in, out := &in.GroupSubtree, &out.GroupSubtree
		*out = new(bool)
		**out = **in
	}
	if in.GroupType != nil {
		in, out := &in.GroupType, &out.GroupType
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupsAsRoles != nil {
		in, out := &in.LdapGroupsAsRoles, &out.LdapGroupsAsRoles
		*out = new(bool)
		**out = **in
	}
	if in.MaxIncidentCount != nil {
		in, out := &in.MaxIncidentCount, &out.MaxIncidentCount
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.UseTrustStore != nil {
		in, out := &in.UseTrustStore, &out.UseTrustStore
		*out = new(bool)
		**out = **in
	}
	if in.UserBaseDn != nil {
		in, out := &in.UserBaseDn, &out.UserBaseDn
		*out = new(string)
		**out = **in
	}
	if in.UserEmailAddressAttribute != nil {
		in, out := &in.UserEmailAddressAttribute, &out.UserEmailAddressAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserLdapFilter != nil {
		in, out := &in.UserLdapFilter, &out.UserLdapFilter
		*out = new(string)
		**out = **in
	}
	if in.UserMemberOfAttribute != nil {
		in, out := &in.UserMemberOfAttribute, &out.UserMemberOfAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectClass != nil {
		in, out := &in.UserObjectClass, &out.UserObjectClass
		*out = new(string)
		**out = **in
	}
	if in.UserPasswordAttribute != nil {
		in, out := &in.UserPasswordAttribute, &out.UserPasswordAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserRealNameAttribute != nil {
		in, out := &in.UserRealNameAttribute, &out.UserRealNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserSubtree != nil {
		in, out := &in.UserSubtree, &out.UserSubtree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapObservation.
func (in *LdapObservation) DeepCopy() *LdapObservation {
	if in == nil {
		return nil
	}
	out := new(LdapObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrder) DeepCopyInto(out *LdapOrder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrder.
func (in *LdapOrder) DeepCopy() *LdapOrder {
	if in == nil {
		return nil
	}
	out := new(LdapOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LdapOrder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrderInitParameters) DeepCopyInto(out *LdapOrderInitParameters) {
	*out = *in
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrderInitParameters.
func (in *LdapOrderInitParameters) DeepCopy() *LdapOrderInitParameters {
	if in == nil {
		return nil
	}
	out := new(LdapOrderInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrderList) DeepCopyInto(out *LdapOrderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LdapOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrderList.
func (in *LdapOrderList) DeepCopy() *LdapOrderList {
	if in == nil {
		return nil
	}
	out := new(LdapOrderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LdapOrderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrderObservation) DeepCopyInto(out *LdapOrderObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrderObservation.
func (in *LdapOrderObservation) DeepCopy() *LdapOrderObservation {
	if in == nil {
		return nil
	}
	out := new(LdapOrderObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrderParameters) DeepCopyInto(out *LdapOrderParameters) {
	*out = *in
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrderParameters.
func (in *LdapOrderParameters) DeepCopy() *LdapOrderParameters {
	if in == nil {
		return nil
	}
	out := new(LdapOrderParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrderSpec) DeepCopyInto(out *LdapOrderSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrderSpec.
func (in *LdapOrderSpec) DeepCopy() *LdapOrderSpec {
	if in == nil {
		return nil
	}
	out := new(LdapOrderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapOrderStatus) DeepCopyInto(out *LdapOrderStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapOrderStatus.
func (in *LdapOrderStatus) DeepCopy() *LdapOrderStatus {
	if in == nil {
		return nil
	}
	out := new(LdapOrderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapParameters) DeepCopyInto(out *LdapParameters) {
	*out = *in
	if in.AuthPasswordSecretRef != nil {
		in, out := &in.AuthPasswordSecretRef, &out.AuthPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AuthRealm != nil {
		in, out := &in.AuthRealm, &out.AuthRealm
		*out = new(string)
		**out = **in
	}
	if in.AuthSchema != nil {
		in, out := &in.AuthSchema, &out.AuthSchema
		*out = new(string)
		**out = **in
	}
	if in.AuthUsername != nil {
		in, out := &in.AuthUsername, &out.AuthUsername
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRetryDelaySeconds != nil {
		in, out := &in.ConnectionRetryDelaySeconds, &out.ConnectionRetryDelaySeconds
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionTimeoutSeconds != nil {
		in, out := &in.ConnectionTimeoutSeconds, &out.ConnectionTimeoutSeconds
		*out = new(float64)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupIDAttribute != nil {
		in, out := &in.GroupIDAttribute, &out.GroupIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberFormat != nil {
		in, out := &in.GroupMemberFormat, &out.GroupMemberFormat
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectClass != nil {
		in, out := &in.GroupObjectClass, &out.GroupObjectClass
		*out = new(string)
		**out = **in
	}
	if in.GroupSubtree != nil {
		in, out := &in.GroupSubtree, &out.GroupSubtree
		*out = new(bool)
		**out = **in
	}
	if in.GroupType != nil {
		in, out := &in.GroupType, &out.GroupType
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.LdapGroupsAsRoles != nil {
		in, out := &in.LdapGroupsAsRoles, &out.LdapGroupsAsRoles
		*out = new(bool)
		**out = **in
	}
	if in.MaxIncidentCount != nil {
		in, out := &in.MaxIncidentCount, &out.MaxIncidentCount
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.UseTrustStore != nil {
		in, out := &in.UseTrustStore, &out.UseTrustStore
		*out = new(bool)
		**out = **in
	}
	if in.UserBaseDn != nil {
		in, out := &in.UserBaseDn, &out.UserBaseDn
		*out = new(string)
		**out = **in
	}
	if in.UserEmailAddressAttribute != nil {
		in, out := &in.UserEmailAddressAttribute, &out.UserEmailAddressAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserLdapFilter != nil {
		in, out := &in.UserLdapFilter, &out.UserLdapFilter
		*out = new(string)
		**out = **in
	}
	if in.UserMemberOfAttribute != nil {
		in, out := &in.UserMemberOfAttribute, &out.UserMemberOfAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectClass != nil {
		in, out := &in.UserObjectClass, &out.UserObjectClass
		*out = new(string)
		**out = **in
	}
	if in.UserPasswordAttribute != nil {
		in, out := &in.UserPasswordAttribute, &out.UserPasswordAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserRealNameAttribute != nil {
		in, out := &in.UserRealNameAttribute, &out.UserRealNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserSubtree != nil {
		in, out := &in.UserSubtree, &out.UserSubtree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapParameters.
func (in *LdapParameters) DeepCopy() *LdapParameters {
	if in == nil {
		return nil
	}
	out := new(LdapParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapSpec) DeepCopyInto(out *LdapSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapSpec.
func (in *LdapSpec) DeepCopy() *LdapSpec {
	if in == nil {
		return nil
	}
	out := new(LdapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapStatus) DeepCopyInto(out *LdapStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapStatus.
func (in *LdapStatus) DeepCopy() *LdapStatus {
	if in == nil {
		return nil
	}
	out := new(LdapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Realms) DeepCopyInto(out *Realms) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Realms.
func (in *Realms) DeepCopy() *Realms {
	if in == nil {
		return nil
	}
	out := new(Realms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Realms) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmsInitParameters) DeepCopyInto(out *RealmsInitParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmsInitParameters.
func (in *RealmsInitParameters) DeepCopy() *RealmsInitParameters {
	if in == nil {
		return nil
	}
	out := new(RealmsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmsList) DeepCopyInto(out *RealmsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Realms, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmsList.
func (in *RealmsList) DeepCopy() *RealmsList {
	if in == nil {
		return nil
	}
	out := new(RealmsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmsObservation) DeepCopyInto(out *RealmsObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmsObservation.
func (in *RealmsObservation) DeepCopy() *RealmsObservation {
	if in == nil {
		return nil
	}
	out := new(RealmsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmsParameters) DeepCopyInto(out *RealmsParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmsParameters.
func (in *RealmsParameters) DeepCopy() *RealmsParameters {
	if in == nil {
		return nil
	}
	out := new(RealmsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmsSpec) DeepCopyInto(out *RealmsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmsSpec.
func (in *RealmsSpec) DeepCopy() *RealmsSpec {
	if in == nil {
		return nil
	}
	out := new(RealmsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmsStatus) DeepCopyInto(out *RealmsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmsStatus.
func (in *RealmsStatus) DeepCopy() *RealmsStatus {
	if in == nil {
		return nil
	}
	out := new(RealmsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Role) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleInitParameters) DeepCopyInto(out *RoleInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Roleid != nil {
		in, out := &in.Roleid, &out.Roleid
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleInitParameters.
func (in *RoleInitParameters) DeepCopy() *RoleInitParameters {
	if in == nil {
		return nil
	}
	out := new(RoleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleList) DeepCopyInto(out *RoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Role, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleList.
func (in *RoleList) DeepCopy() *RoleList {
	if in == nil {
		return nil
	}
	out := new(RoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleObservation) DeepCopyInto(out *RoleObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Roleid != nil {
		in, out := &in.Roleid, &out.Roleid
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleObservation.
func (in *RoleObservation) DeepCopy() *RoleObservation {
	if in == nil {
		return nil
	}
	out := new(RoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleParameters) DeepCopyInto(out *RoleParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Roleid != nil {
		in, out := &in.Roleid, &out.Roleid
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleParameters.
func (in *RoleParameters) DeepCopy() *RoleParameters {
	if in == nil {
		return nil
	}
	out := new(RoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleSpec.
func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStatus) DeepCopyInto(out *RoleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatus.
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAML) DeepCopyInto(out *SAML) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAML.
func (in *SAML) DeepCopy() *SAML {
	if in == nil {
		return nil
	}
	out := new(SAML)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAML) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLInitParameters) DeepCopyInto(out *SAMLInitParameters) {
	*out = *in
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.EntityID != nil {
		in, out := &in.EntityID, &out.EntityID
		*out = new(string)
		**out = **in
	}
	if in.FirstNameAttribute != nil {
		in, out := &in.FirstNameAttribute, &out.FirstNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupsAttribute != nil {
		in, out := &in.GroupsAttribute, &out.GroupsAttribute
		*out = new(string)
		**out = **in
	}
	if in.IdpMetadata != nil {
		in, out := &in.IdpMetadata, &out.IdpMetadata
		*out = new(string)
		**out = **in
	}
	if in.LastNameAttribute != nil {
		in, out := &in.LastNameAttribute, &out.LastNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UsernameAttribute != nil {
		in, out := &in.UsernameAttribute, &out.UsernameAttribute
		*out = new(string)
		**out = **in
	}
	if in.ValidateAssertionSignature != nil {
		in, out := &in.ValidateAssertionSignature, &out.ValidateAssertionSignature
		*out = new(bool)
		**out = **in
	}
	if in.ValidateResponseSignature != nil {
		in, out := &in.ValidateResponseSignature, &out.ValidateResponseSignature
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLInitParameters.
func (in *SAMLInitParameters) DeepCopy() *SAMLInitParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLList) DeepCopyInto(out *SAMLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SAML, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLList.
func (in *SAMLList) DeepCopy() *SAMLList {
	if in == nil {
		return nil
	}
	out := new(SAMLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLObservation) DeepCopyInto(out *SAMLObservation) {
	*out = *in
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.EntityID != nil {
		in, out := &in.EntityID, &out.EntityID
		*out = new(string)
		**out = **in
	}
	if in.FirstNameAttribute != nil {
		in, out := &in.FirstNameAttribute, &out.FirstNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupsAttribute != nil {
		in, out := &in.GroupsAttribute, &out.GroupsAttribute
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdpMetadata != nil {
		in, out := &in.IdpMetadata, &out.IdpMetadata
		*out = new(string)
		**out = **in
	}
	if in.LastNameAttribute != nil {
		in, out := &in.LastNameAttribute, &out.LastNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UsernameAttribute != nil {
		in, out := &in.UsernameAttribute, &out.UsernameAttribute
		*out = new(string)
		**out = **in
	}
	if in.ValidateAssertionSignature != nil {
		in, out := &in.ValidateAssertionSignature, &out.ValidateAssertionSignature
		*out = new(bool)
		**out = **in
	}
	if in.ValidateResponseSignature != nil {
		in, out := &in.ValidateResponseSignature, &out.ValidateResponseSignature
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLObservation.
func (in *SAMLObservation) DeepCopy() *SAMLObservation {
	if in == nil {
		return nil
	}
	out := new(SAMLObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLParameters) DeepCopyInto(out *SAMLParameters) {
	*out = *in
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.EntityID != nil {
		in, out := &in.EntityID, &out.EntityID
		*out = new(string)
		**out = **in
	}
	if in.FirstNameAttribute != nil {
		in, out := &in.FirstNameAttribute, &out.FirstNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupsAttribute != nil {
		in, out := &in.GroupsAttribute, &out.GroupsAttribute
		*out = new(string)
		**out = **in
	}
	if in.IdpMetadata != nil {
		in, out := &in.IdpMetadata, &out.IdpMetadata
		*out = new(string)
		**out = **in
	}
	if in.LastNameAttribute != nil {
		in, out := &in.LastNameAttribute, &out.LastNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UsernameAttribute != nil {
		in, out := &in.UsernameAttribute, &out.UsernameAttribute
		*out = new(string)
		**out = **in
	}
	if in.ValidateAssertionSignature != nil {
		in, out := &in.ValidateAssertionSignature, &out.ValidateAssertionSignature
		*out = new(bool)
		**out = **in
	}
	if in.ValidateResponseSignature != nil {
		in, out := &in.ValidateResponseSignature, &out.ValidateResponseSignature
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLParameters.
func (in *SAMLParameters) DeepCopy() *SAMLParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSpec) DeepCopyInto(out *SAMLSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSpec.
func (in *SAMLSpec) DeepCopy() *SAMLSpec {
	if in == nil {
		return nil
	}
	out := new(SAMLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLStatus) DeepCopyInto(out *SAMLStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLStatus.
func (in *SAMLStatus) DeepCopy() *SAMLStatus {
	if in == nil {
		return nil
	}
	out := new(SAMLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststore) DeepCopyInto(out *SSLTruststore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststore.
func (in *SSLTruststore) DeepCopy() *SSLTruststore {
	if in == nil {
		return nil
	}
	out := new(SSLTruststore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSLTruststore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststoreInitParameters) DeepCopyInto(out *SSLTruststoreInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststoreInitParameters.
func (in *SSLTruststoreInitParameters) DeepCopy() *SSLTruststoreInitParameters {
	if in == nil {
		return nil
	}
	out := new(SSLTruststoreInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststoreList) DeepCopyInto(out *SSLTruststoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SSLTruststore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststoreList.
func (in *SSLTruststoreList) DeepCopy() *SSLTruststoreList {
	if in == nil {
		return nil
	}
	out := new(SSLTruststoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSLTruststoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststoreObservation) DeepCopyInto(out *SSLTruststoreObservation) {
	*out = *in
	if in.Fingerprint != nil {
		in, out := &in.Fingerprint, &out.Fingerprint
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststoreObservation.
func (in *SSLTruststoreObservation) DeepCopy() *SSLTruststoreObservation {
	if in == nil {
		return nil
	}
	out := new(SSLTruststoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststoreParameters) DeepCopyInto(out *SSLTruststoreParameters) {
	*out = *in
	out.PemSecretRef = in.PemSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststoreParameters.
func (in *SSLTruststoreParameters) DeepCopy() *SSLTruststoreParameters {
	if in == nil {
		return nil
	}
	out := new(SSLTruststoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststoreSpec) DeepCopyInto(out *SSLTruststoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
	out.InitProvider = in.InitProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststoreSpec.
func (in *SSLTruststoreSpec) DeepCopy() *SSLTruststoreSpec {
	if in == nil {
		return nil
	}
	out := new(SSLTruststoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLTruststoreStatus) DeepCopyInto(out *SSLTruststoreStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLTruststoreStatus.
func (in *SSLTruststoreStatus) DeepCopy() *SSLTruststoreStatus {
	if in == nil {
		return nil
	}
	out := new(SSLTruststoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserInitParameters) DeepCopyInto(out *UserInitParameters) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Firstname != nil {
		in, out := &in.Firstname, &out.Firstname
		*out = new(string)
		**out = **in
	}
	if in.Lastname != nil {
		in, out := &in.Lastname, &out.Lastname
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Userid != nil {
		in, out := &in.Userid, &out.Userid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserInitParameters.
func (in *UserInitParameters) DeepCopy() *UserInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserObservation) DeepCopyInto(out *UserObservation) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Firstname != nil {
		in, out := &in.Firstname, &out.Firstname
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Lastname != nil {
		in, out := &in.Lastname, &out.Lastname
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Userid != nil {
		in, out := &in.Userid, &out.Userid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserObservation.
func (in *UserObservation) DeepCopy() *UserObservation {
	if in == nil {
		return nil
	}
	out := new(UserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserParameters) DeepCopyInto(out *UserParameters) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Firstname != nil {
		in, out := &in.Firstname, &out.Firstname
		*out = new(string)
		**out = **in
	}
	if in.Lastname != nil {
		in, out := &in.Lastname, &out.Lastname
		*out = new(string)
		**out = **in
	}
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Userid != nil {
		in, out := &in.Userid, &out.Userid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserParameters.
func (in *UserParameters) DeepCopy() *UserParameters {
	if in == nil {
		return nil
	}
	out := new(UserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpec) DeepCopyInto(out *UserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpec.
func (in *UserSpec) DeepCopy() *UserSpec {
	if in == nil {
		return nil
	}
	out := new(UserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStatus) DeepCopyInto(out *UserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStatus.
func (in *UserStatus) DeepCopy() *UserStatus {
	if in == nil {
		return nil
	}
	out := new(UserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserToken) DeepCopyInto(out *UserToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserToken.
func (in *UserToken) DeepCopy() *UserToken {
	if in == nil {
		return nil
	}
	out := new(UserToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenInitParameters) DeepCopyInto(out *UserTokenInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpirationDays != nil {
		in, out := &in.ExpirationDays, &out.ExpirationDays
		*out = new(float64)
		**out = **in
	}
	if in.ExpirationEnabled != nil {
		in, out := &in.ExpirationEnabled, &out.ExpirationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProtectContent != nil {
		in, out := &in.ProtectContent, &out.ProtectContent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenInitParameters.
func (in *UserTokenInitParameters) DeepCopy() *UserTokenInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserTokenInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenList) DeepCopyInto(out *UserTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenList.
func (in *UserTokenList) DeepCopy() *UserTokenList {
	if in == nil {
		return nil
	}
	out := new(UserTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenObservation) DeepCopyInto(out *UserTokenObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpirationDays != nil {
		in, out := &in.ExpirationDays, &out.ExpirationDays
		*out = new(float64)
		**out = **in
	}
	if in.ExpirationEnabled != nil {
		in, out := &in.ExpirationEnabled, &out.ExpirationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProtectContent != nil {
		in, out := &in.ProtectContent, &out.ProtectContent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenObservation.
func (in *UserTokenObservation) DeepCopy() *UserTokenObservation {
	if in == nil {
		return nil
	}
	out := new(UserTokenObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenParameters) DeepCopyInto(out *UserTokenParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpirationDays != nil {
		in, out := &in.ExpirationDays, &out.ExpirationDays
		*out = new(float64)
		**out = **in
	}
	if in.ExpirationEnabled != nil {
		in, out := &in.ExpirationEnabled, &out.ExpirationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProtectContent != nil {
		in, out := &in.ProtectContent, &out.ProtectContent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenParameters.
func (in *UserTokenParameters) DeepCopy() *UserTokenParameters {
	if in == nil {
		return nil
	}
	out := new(UserTokenParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenSpec) DeepCopyInto(out *UserTokenSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenSpec.
func (in *UserTokenSpec) DeepCopy() *UserTokenSpec {
	if in == nil {
		return nil
	}
	out := new(UserTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenStatus) DeepCopyInto(out *UserTokenStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenStatus.
func (in *UserTokenStatus) DeepCopy() *UserTokenStatus {
	if in == nil {
		return nil
	}
	out := new(UserTokenStatus)
	in.DeepCopyInto(out)
	return out
}
