// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SSLTruststoreInitParameters struct {
}

type SSLTruststoreObservation struct {

	// (String) The fingerprint of the cert
	// The fingerprint of the cert
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// (String) Used to identify resource at nexus
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SSLTruststoreParameters struct {

	// (String) The cert in PEM format
	// The cert in PEM format
	// +kubebuilder:validation:Optional
	PemSecretRef v1.SecretKeySelector `json:"pemSecretRef" tf:"-"`
}

// SSLTruststoreSpec defines the desired state of SSLTruststore
type SSLTruststoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SSLTruststoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SSLTruststoreInitParameters `json:"initProvider,omitempty"`
}

// SSLTruststoreStatus defines the observed state of SSLTruststore.
type SSLTruststoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SSLTruststoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SSLTruststore is the Schema for the SSLTruststores API. Use this resource to add an SSL certificate to the nexus Truststore
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nexus}
type SSLTruststore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pemSecretRef)",message="spec.forProvider.pemSecretRef is a required parameter"
	Spec   SSLTruststoreSpec   `json:"spec"`
	Status SSLTruststoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SSLTruststoreList contains a list of SSLTruststores
type SSLTruststoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SSLTruststore `json:"items"`
}

// Repository type metadata.
var (
	SSLTruststore_Kind             = "SSLTruststore"
	SSLTruststore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SSLTruststore_Kind}.String()
	SSLTruststore_KindAPIVersion   = SSLTruststore_Kind + "." + CRDGroupVersion.String()
	SSLTruststore_GroupVersionKind = CRDGroupVersion.WithKind(SSLTruststore_Kind)
)

func init() {
	SchemeBuilder.Register(&SSLTruststore{}, &SSLTruststoreList{})
}
