apiVersion: blobstore.nexus.adrp.xyz/v1alpha1
kind: Azure
metadata:
  annotations:
    meta.upbound.io/example-id: blobstore/v1alpha1/azure
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketConfiguration:
    - accountName: example-account-name
      authentication:
      - accountKey: example-account-key
        authenticationMethod: ACCOUNTKEY
      containerName: example-container-name
    name: example
    softQuota:
    - limit: 1024
      type: spaceRemainingQuota
