name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: upbound/official-providers-ci/.github/workflows/pr-comment-trigger.yml@44c3fe875827c37d9621c0b9221052313738fd6f #v0.12.0
    secrets:
      UPTEST_CLOUD_CREDENTIALS: ${{ secrets.UPTEST_CLOUD_CREDENTIALS }}
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_DATASOURCE }}
