name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: upbound/official-providers-ci/.github/workflows/pr-comment-trigger.yml@427547fd7b8c583daa4cacdec0ecb5d95f598448 # v0.12.1
    secrets:
      UPTEST_CLOUD_CREDENTIALS: ${{ secrets.UPTEST_CLOUD_CREDENTIALS }}
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_DATASOURCE }}
